import random

def Jokes():
    list = ['Why did the chicken cross the road? To go to the other side',
                'A man in a hotel: Waiter, there is a dead fly in my bean soup.' + str('</p><p class="botText"><span>') + 'Waiter: Oh, the hot soup must have killed it sir.',
                'Wife: Why do you wear your specs only when I come in.' + str('</p><p class="botText"><span>') + 'Husband: The doctor has ordered me to wear my specs whenever I get an headache.',
                'Customer in a hotel: Waiter, this soup tastes funny!'+ str('</p><p class="botText"><span>') + 'Waiter: Oh!, the chef must have been laughing when he prepared it sir.',
                'Man 1: My son does not listen to anything that I say.'+ str('</p><p class="botText"><span>') + 'Man 2: Is he so adamnant?'+ str('</p><p class="botText"><span>') + 'Man 1: No, he is deaf.',
                'Teacher: "Amy, what do you call the outside of a tree?"'+ str('</p><p class="botText"><span>') + 'Student: "No idea miss"'+ str('</p><p class="botText"><span>') + 'Teacher told angrily: "Bark, Amy".'+ str('</p><p class="botText"><span>') + 'Amy: "Bow Wow Wow Miss"',
                'Friend 1: Is it true that your wife talks to herself when she is alone?'+ str('</p><p class="botText"><span>') + 'Friend 2: I do not know. I was not with her when she was alone.',
                'Man to miser: Why do you always remove the batteries from the clock and keep them outside?'+ str('</p><p class="botText"><span>') + 'Miser: I want to extend the battery life and hence I put them in the clock only when I want to see the time.',
                'Employee: I got to have salary increment. Three other companies are after me.'+ str('</p><p class="botText"><span>') + 'Boss: Really? Which are the three companies?'+ str('</p><p class="botText"><span>') + 'Employee: The electric company, the telephone company and the gas company.',
                'Why should not you hold a DVD upside down?'+ str('</p><p class="botText"><span>') + 'Because the data might fall down.',
                'When asked how he would like to die, this man told:'+ str('</p><p class="botText"><span>') + 'I would like to die just like my grand father did,'+ str('</p><p class="botText"><span>') + 'Peacefully in his sleep,not screeming or yelling like the'+ str('</p><p class="botText"><span>') +'passengers in the car he was driving',
                'I wish I was a billionaire, just like my dad'+ str('</p><p class="botText"><span>') +'Oh, so your dad was a billionaire?'+ str('</p><p class="botText"><span>') +'No, he also wished he were.',
                'I broke my finger last week.'+ str('</p><p class="botText"><span>') +'On the other hand, I’m okay',
                'Two blind dudes are fighting really viciously. How do you stop them?' + str('</p><p class="botText"><span>') + 'You shout, “I’m betting on the dude with the knife!”',
                'Why do scuba divers fall backwards off of the boat?'+ str('</p><p class="botText"><span>') +'Because if they fell forward, they’d still be on the boat.',
                'What’s the difference between a bird and a fly? A bird can fly but a fly can’t bird',
                'What day do chickens hate most?'+ str('</p><p class="botText"><span>') +'Fry-day!',
                'Listening to a spouse is like reading the terms and conditions of a website.'+ str('</p><p class="botText"><span>') +'You understand nothing, but you still say, "I agree"',
                'What Kind Of Tree Grows In Your Hand?'+ str('</p><p class="botText"><span>') +'A palmtree',
                'What Room Can No One Enter ?'+ str('</p><p class="botText"><span>') +'A mushroom',
                'What is the best thing about Switzerland? I don not know, but their flag is a huge plus.',
                'What is Karma?'+ str('</p><p class="botText"><span>') +'Parents who bunked classes decades ago...'+ str('</p><p class="botText"><span>') +'now attending their kids’ online classes with them',
                'Two men meet on opposite sides of a river.'+ str('</p><p class="botText"><span>') +'One shouts to the other, "I need you to help me get to the other side!"'+ str('</p><p class="botText"><span>') +'The other guy replies, "You are on the other side!"',
                'What did the mayonnaise say when the refrigerator door was opened? Close the door, I am dressing.',
                ' I told my physical therapist that I broke my arm in two places. He told me to stop going to those places.',
                'How do you make holy water? You boil the hell out of it.',
                'What do you call a bee that can’t make up its mind? A maybe.',
                'Where do cows go for fun?'+ str('</p><p class="botText"><span>') +'To the moo-vies.',
                'How do bees go to school?'+ str('</p><p class="botText"><span>') +'On a school buzz!',
                'What did baby corn ask mama-corn?'+ str('</p><p class="botText"><span>') +'Where is POP-corn!!',
                'Why did the nurse needed a red pen? '+ str('</p><p class="botText"><span>') +'Incase she wanted to draw blood',]

    return (random.choice(list))